apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: angular_k8s_deployment:1.0 #docker image already create with docker file
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
  type: NodePort

